### ISSUE TITLE
Could you please clarify one of the paths required?

### ISSUE THREAD

**Issue by JamiePike** [pvdam3/FoEC#2]
Hello, 
I am having a little trouble working out exactly what is required for the blastdatabasedir path. What should be contained within this directory? Is it the output of makeblastdb? If so, must I first perform makeblastdb on my genomes and why would these not be provided with the testdata? 

The default of path in FoEC.py:

`blastdatabasedir                        = '/Users/Peter/Documents/Sequences/Fo_genomes/blastdbs'`

Thank you,
Jamie

**Comment by pvdam3** [comment]
Hi Jamie, 
the blast db directory is where the blast databases will be stored. These will be made using the blast+ software makeblastdb when running the script so you don't need to perform it separately yourself.
Peter
